CREATE user suuser WITH PASSWORD 'suuser';

CREATE DATABASE usersdb;
CREATE DATABASE booksdb;
CREATE DATABASE issuesdb;

GRANT ALL PRIVILEGES ON DATABASE usersdb TO suuser;
GRANT ALL PRIVILEGES ON DATABASE booksdb TO suuser;
GRANT ALL PRIVILEGES ON DATABASE issuesdb TO suuser;